[package]
name = "ota"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.6.0", default-features = false }
